apiVersion: v1
kind: Service
metadata:
  name: {{ include "phpldapadmin.fullname" . }}
  labels:
    {{- include "phpldapadmin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "phpldapadmin.selectorLabels" . | nindent 4 }}
