realm: "keycloakOpa"
enabled: true
displayName: "keycloakOpa"

loginWithEmailAllowed: true
resetPasswordAllowed: true

loginTheme: keycloak
accountTheme: keycloak.v3
emailTheme: keycloak

eventsListeners:
  - "jboss-logging"
  - "custom-event-listener"

eventsEnabled: true

clientScopes:
  - name: "rabbitmq.read"
    description: "RabbitMQ read permissions"
    protocol: "openid-connect"
    attributes:
      "include.in.token.scope": "true"
      "display.on.consent.screen": "false"
  - name: "rabbitmq.write"
    description: "RabbitMQ write permissions"
    protocol: "openid-connect"
    attributes:
      "include.in.token.scope": "true"
      "display.on.consent.screen": "false"
  - name: "rabbitmq.configure"
    description: "RabbitMQ configure permissions"
    protocol: "openid-connect"
    attributes:
      "include.in.token.scope": "true"
      "display.on.consent.screen": "false"
  - name: "rabbitmq-audience"
    description: "RabbitMQ audience claim"
    protocol: "openid-connect"
    protocolMappers:  
      - name: "rabbitmq-aud-mapper"
        protocol: "openid-connect"
        protocolMapper: "oidc-audience-mapper"
        consentRequired: false
        config:
          "included.custom.audience": "rabbitmq"
          "access.token.claim": "true"

clients:
  - clientId: kck
    protocol: openid-connect
    name: kck
    description: "kck - AMQP applications"
    enabled: true
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    alwaysDisplayInConsole: true
    serviceAccountsEnabled: true
    fullScopeAllowed: false
    secret: "secret"
    defaultClientScopes:
      - "profile"
      - "email"
      - "rabbitmq.read"
      - "rabbitmq.write"
      - "rabbitmq-audience"
  - clientId: "rabbitmq-producer"
    protocol: openid-connect
    name: "RabbitMQ Producer Client"
    description: "Client for RabbitMQ producers"
    enabled: true
    publicClient: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: true
    alwaysDisplayInConsole: true
    serviceAccountsEnabled: true
    fullScopeAllowed: false
    secret: "producer-secret-change-me"
    defaultClientScopes:
      - "rabbitmq.write"
  - clientId: "rabbitmq-consumer"
    protocol: openid-connect
    name: "RabbitMQ Consumer Client"
    description: "Client for RabbitMQ consumers"
    enabled: true
    publicClient: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: true
    alwaysDisplayInConsole: true
    serviceAccountsEnabled: true
    fullScopeAllowed: false
    secret: "consumer-secret-change-me"
    defaultClientScopes:
      - "rabbitmq.read"
  - clientId: rabbitmq-management
    name: rabbitmq-management
    description: "rabbitmq-management"
    enabled: true
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    alwaysDisplayInConsole: true
    serviceAccountsEnabled: true
    fullScopeAllowed: false
    secret: "secret"

userFederationProviders:
  - displayName: "ldap"
    providerName: "ldap"
    config:
      enabled: "true"
      vendor: "other"
      connectionUrl: "ldap://access-control-openldap"
      useTruststoreSpi: "always"
      connectionPooling: "false"
      bindType: "simple"
      bindDn: "cn=admin,dc=example,dc=org"
      bindCredential: "Acc3ss@C0ntr0L_"
      editMode: "READ_ONLY"
      usersDn: "ou=users,dc=example,dc=org"
      usernameLDAPAttribute: "uid"
      rdnLDAPAttribute: "uid"
      uuidLDAPAttribute: "entryUUID"
      userObjectClasses: "inetOrgPerson, organizationalPerson"
      searchScope: "1"
      pagination: "false"
      referrals: "ignore"
      importEnabled: "true"
      syncRegistrations: "true"
      allowKerberosAuthentication: "false"
      useKerberosForPasswordAuthentication: "false"
      cachePolicy: "DEFAULT"
      validatePasswordPolicy: "false"
      trustEmail: "false"
      enablePasswordModifyExtendedOp: "false"

userFederationMappers:
  - name: "first name"
    id: "firstNameMapper"
    federationProviderDisplayName: "ldap"
    federationMapperType: "user-attribute-ldap-mapper"
    config:
      user.model.attribute: "firstName"
      ldap.attribute: "cn"
      read.only: "true"
      always.read.value.from.ldap: "true"
      is.mandatory.in.ldap: "true"
      attribute.default.value: "false"
      is.binary.attribute: "false"
  - name: "last name"
    id: "lastNameMapper"
    federationProviderDisplayName: "ldap"
    federationMapperType: "user-attribute-ldap-mapper"
    config:
      user.model.attribute: "lastName"
      ldap.attribute: "sn"
      read.only: "true"
      always.read.value.from.ldap: "true"
      is.mandatory.in.ldap: "true"
      attribute.default.value: "false"
      is.binary.attribute: "false"
  - name: "username"
    id: "usernameMapper"
    federationProviderDisplayName: "ldap"
    federationMapperType: "user-attribute-ldap-mapper"
    config:
      user.model.attribute: "username"
      ldap.attribute: "uid"
      read.only: "true"
      always.read.value.from.ldap: "false"
      is.mandatory.in.ldap: "true"
      attribute.default.value: "false"
      is.binary.attribute: "false"
  - name: "roles"
    id: "roleMapper"
    federationProviderDisplayName: "ldap"
    federationMapperType: "role-ldap-mapper"
    config:
      roles.dn: "ou=roles,dc=example,dc=org"
      role.name.ldap.attribute: "cn"
      role.object.classes: "posixGroup"
      membership.ldap.attribute: "memberUid"
      membership.attribute.type: "UID"
      membership.user.ldap.attribute: "uid" 
      mode: "READ_ONLY"
      user.roles.retrieve.strategy: "LOAD_ROLES_BY_MEMBER_ATTRIBUTE"
      memberof.ldap.attribute: "memberOf"
      use.realm.roles.mapping: "true"
